### ISSUE TITLE
Shell Sort

### ISSUE THREAD

**Issue by prasadvpatil** [salonishah01/DSA_Python#2]
## 💥 Proposal

Shell sort is a generalized version of insertion sort. It overcomes the drawbacks of insertion sort by comparing elements separated by a gap of several positions. In general, Shell sort performs the following steps.

Step 1: Arrange the elements in the tabular form and sort the columns by using insertion sort.
Step 2: Repeat Step 1; each time with smaller number of longer columns in such a way that at the end, there is only one column of data to be sorted.

### Have you read the [Contributing Guidelines on Pull Requests]

Yes

**Comment by KarlssonLucas** [comment]
Hey, can you assign me to the issue?

**Comment by salonishah01** [comment]
@KarlssonLucas You can create new issues, this one is already taken.
