### ISSUE TITLE
Quick Sort

### ISSUE THREAD

**Issue by prasadvpatil** [salonishah01/DSA_Python#4]
## 💥 Proposal

Quick sort is a highly efficient sorting algorithm and is based on partitioning of array of data into smaller arrays. A large array is partitioned into two arrays one of which holds values smaller than the specified value, say pivot, based on which the partition is made and another array holds values greater than the pivot value.

### Have you read the [Contributing Guidelines on Pull Requests]

Yes

**Comment by megabyte98** [comment]
Can you please assign this issue to me I would like to contribute.

**Comment by salonishah01** [comment]
@megabyte98 Prasad has already generated a pull request for same already.
You can generate any other issue, and work on that.
