### ISSUE TITLE
Bubble Sort

### ISSUE THREAD

**Issue by prasadvpatil** [salonishah01/DSA_Python#6]
## 💥 Proposal

Bubble sort is a simple sorting algorithm. This sorting algorithm is comparison-based algorithm in which each pair of adjacent elements is compared and the elements are swapped if they are not in order. This algorithm is not suitable for large data sets as its average and worst case complexity are of Ο(n^2) where n is the number of items.

### Have you read the [Contributing Guidelines on Pull Requests]

Yes

**Comment by martinh-dev** [comment]
Hey @prasadvpatil, can you please assign this issue to me I would like to work on it.

**Comment by SardulDhyani** [comment]
Hi @prasadvpatil Please assign this issue to me

**Comment by prasadvpatil** [comment]
Hey @martinh-dev and @SardulDhyani Sorry i have done PR for the same issue. 
But you can still contribute to Data Structure Algorithms in my Repo,
 https://github.com/prasadvpatil/Data-Structure-Algorithms
1) Fork the repo 
2) Create or ask to work for an Issue
3) Start contributing and pull request.
